version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"
    volumes:
      - ./:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PRICES_FOLDER=${PRICES_FOLDER}
    networks:
      - www
networks:
  www: